name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: bash

env:
  GO_VERSION: 1.23.6

jobs:
  build:
    name: build package, run linter
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: '~${{ env.GO_VERSION }}'

      - name: compile
        run: make build

      - name: lint
        run: make lint

      - name: unit-race
        run: make unit-race
